# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
warnings_are_errors: false
before_install:
  - tlmgr install index
cache: packages
after_success:
  - Rscript -e 'covr::codecov()'
after_success:
  - Rscript -e 'covr::coveralls()'
